# fly.toml file generated for dental-bot on 2022-11-23T12:41:43+01:00

app = "dental-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
